[package]
name = "todo_api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
hyper = {version = "1.5.2", features = ["full"]}
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.134"
tokio = {version = "1.42.0", features = ["full"]}
tracing-subscriber = "0.3.19"
