[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.23", features = ["derive"]}
serde = {version = "1.0.216", features = ["derive"]}
serde_json = {version = "1.0.134"}
