[package]
name = "TaskFlowTokio"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel", "crossbeam-queue"] }
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["full"] }
